import * as XLSX from "xlsx";
import { PUBLIC_PHOTOS, PUBLIC_DOCUMENTS, assetUrl } from "./public-assets";

type InspectionRecord = Record<string, string>;

// Equipment registry — matches QR codes generated by the system
const EQUIPMENT_REGISTRY = [
  { id: "BLR-001", description: "Building 740 Main Boiler",           type: "Boiler" },
  { id: "BLR-002", description: "Building 740 Secondary Boiler",      type: "Boiler" },
  { id: "HVAC-001", description: "Building 740 Main Air Handler (AHU)", type: "HVAC" },
  { id: "HVAC-002", description: "Building 704 Rooftop Unit",          type: "HVAC" },
  { id: "PV-001",  description: "Lab A Pressure Vessel",               type: "Pressure Vessel" },
  { id: "PV-002",  description: "Mechanical Room Pressure Vessel",     type: "Pressure Vessel" },
  { id: "FS-001",  description: "Building 740 Fire Suppression System", type: "Fire Suppression" },
  { id: "FS-002",  description: "Building 704 Fire Suppression System", type: "Fire Suppression" },
];

// All checklist fields per equipment type
const CHECKLIST_TEMPLATES = [
  { type: "Boiler",           key: "pressure",          label: "Pressure",            dataType: "number", unit: "PSI",  options: "" },
  { type: "Boiler",           key: "temperature",       label: "Temperature",         dataType: "number", unit: "°F",   options: "" },
  { type: "Boiler",           key: "waterLevel",        label: "Water Level",         dataType: "select", unit: "",     options: "Normal | Low | High" },
  { type: "Boiler",           key: "safetyValve",       label: "Safety Valve",        dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "Boiler",           key: "lowWaterCutoff",    label: "Low-Water Cutoff",    dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "Boiler",           key: "flameSafeguard",    label: "Flame Safeguard",     dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "HVAC",             key: "temperature",       label: "Temperature",         dataType: "number", unit: "°F",   options: "" },
  { type: "HVAC",             key: "filterCondition",   label: "Filter Condition",    dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "HVAC",             key: "refrigerantLevel",  label: "Refrigerant Level",   dataType: "select", unit: "",     options: "Normal | Low" },
  { type: "HVAC",             key: "thermostat",        label: "Thermostat",          dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "HVAC",             key: "ductwork",          label: "Ductwork",            dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "Pressure Vessel",  key: "pressure",          label: "Pressure",            dataType: "number", unit: "PSI",  options: "" },
  { type: "Pressure Vessel",  key: "safetyReliefValve", label: "Safety Relief Valve", dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "Pressure Vessel",  key: "shellCondition",    label: "Shell Condition",     dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "Pressure Vessel",  key: "fittings",          label: "Fittings",            dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "Fire Suppression", key: "gaugePressure",     label: "Gauge Pressure",      dataType: "number", unit: "PSI",  options: "" },
  { type: "Fire Suppression", key: "tamperSeal",        label: "Tamper Seal",         dataType: "select", unit: "",     options: "Intact | Broken" },
  { type: "Fire Suppression", key: "signage",           label: "Signage",             dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "Fire Suppression", key: "accessClear",       label: "Access Clear",        dataType: "select", unit: "",     options: "Pass | Fail" },
  { type: "Other",            key: "generalCondition",  label: "General Condition",   dataType: "select", unit: "",     options: "Pass | Fail" },
];

function buildDashboardSheet(records: InspectionRecord[]): XLSX.WorkSheet {
  const total   = records.length;
  const passed  = records.filter((r) => r["Result"] === "Pass").length;
  const attn    = records.filter((r) => r["Result"] === "Attention").length;
  const failed  = records.filter((r) => r["Result"] === "Fail").length;
  const passRate = total > 0 ? `${Math.round((passed / total) * 100)}%` : "N/A";

  const typeCounts = EQUIPMENT_REGISTRY.reduce<Record<string, number>>((acc, eq) => {
    acc[eq.type] = (acc[eq.type] || 0) +
      records.filter((r) => r["ID"] === eq.id).length;
    return acc;
  }, {});

  const latestDate = records.length > 0
    ? new Date(records[0]["Date"] || "").toLocaleDateString()
    : "None";

  const rows: (string | number)[][] = [
    ["WVRTP Equipment Inspection Workbook"],
    ["West Virginia Regional Technology Park"],
    [],
    ["Generated:", new Date().toLocaleString()],
    ["Latest Inspection:", latestDate],
    [],
    ["── SUMMARY STATISTICS ──────────────────────────"],
    ["Total Inspections:", total],
    ["Pass:",             passed],
    ["Attention:",        attn],
    ["Fail:",             failed],
    ["Pass Rate:",        passRate],
    [],
    ["── INSPECTIONS BY EQUIPMENT TYPE ──────────────"],
    ["Boiler:",           typeCounts["Boiler"] ?? 0],
    ["HVAC:",             typeCounts["HVAC"] ?? 0],
    ["Pressure Vessel:",  typeCounts["Pressure Vessel"] ?? 0],
    ["Fire Suppression:", typeCounts["Fire Suppression"] ?? 0],
    ["Other:",            records.filter((r) => !["Boiler","HVAC","Pressure Vessel","Fire Suppression"].includes(r["Equipment Type"])).length],
    [],
    ["── SHEETS IN THIS WORKBOOK ────────────────────"],
    ["Inspection Log",       "All submitted inspection records"],
    ["Equipment Registry",   "Registered equipment with QR code links"],
    ["Checklist Templates",  "Inspection fields required per equipment type"],
    ["Photo Gallery",        "Reference photographs (linked to web app)"],
    ["Reference Documents",  "Technical checklists and operator guides"],
  ];

  const ws = XLSX.utils.aoa_to_sheet(rows);

  ws["!cols"] = [{ wch: 35 }, { wch: 52 }];
  ws["!rows"] = [{ hpt: 22 }, { hpt: 16 }];

  return ws;
}

function buildInspectionLogSheet(records: InspectionRecord[]): XLSX.WorkSheet {
  const allChecklist = [
    "pressure","temperature","waterLevel","safetyValve","lowWaterCutoff","flameSafeguard",
    "filterCondition","refrigerantLevel","thermostat","ductwork",
    "safetyReliefValve","shellCondition","fittings",
    "gaugePressure","tamperSeal","signage","accessClear",
    "generalCondition",
  ];

  const header = [
    "ID","Equipment Type","Inspector","Result","Date","Latitude","Longitude",
    "Address","Notes","Photo",
    ...allChecklist,
  ];

  const rows: (string | number)[][] = [header];

  for (const rec of records) {
    rows.push(header.map((col) => rec[col] ?? ""));
  }

  const ws = XLSX.utils.aoa_to_sheet(rows);

  ws["!cols"] = [
    { wch: 10 }, { wch: 18 }, { wch: 18 }, { wch: 11 }, { wch: 22 },
    { wch: 12 }, { wch: 12 }, { wch: 36 }, { wch: 30 }, { wch: 20 },
    ...Array(allChecklist.length).fill({ wch: 18 }),
  ];

  return ws;
}

function buildEquipmentRegistrySheet(): XLSX.WorkSheet {
  const appBase = window.location.origin;

  const header = ["Equipment ID", "Description", "Type", "QR Scan URL"];
  const rows: (string | number)[][] = [header];

  for (const eq of EQUIPMENT_REGISTRY) {
    const scanUrl = `${appBase}/#/inspect?id=${eq.id}`;
    rows.push([eq.id, eq.description, eq.type, scanUrl]);
  }

  const ws = XLSX.utils.aoa_to_sheet(rows);

  // Add hyperlinks on the QR Scan URL column (column D = index 3)
  EQUIPMENT_REGISTRY.forEach((eq, i) => {
    const cellAddr = XLSX.utils.encode_cell({ r: i + 1, c: 3 });
    const scanUrl  = `${appBase}/#/inspect?id=${eq.id}`;
    ws[cellAddr] = { v: scanUrl, l: { Target: scanUrl, Tooltip: `Open inspection form for ${eq.id}` } };
  });

  ws["!cols"] = [{ wch: 14 }, { wch: 38 }, { wch: 18 }, { wch: 52 }];

  return ws;
}

function buildChecklistTemplatesSheet(): XLSX.WorkSheet {
  const header = ["Equipment Type", "Field Key", "Label", "Data Type", "Unit", "Allowed Values"];
  const rows: (string | number)[][] = [
    header,
    ...CHECKLIST_TEMPLATES.map((t) => [
      t.type, t.key, t.label, t.dataType, t.unit, t.options,
    ]),
  ];

  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws["!cols"] = [{ wch: 18 }, { wch: 20 }, { wch: 22 }, { wch: 10 }, { wch: 8 }, { wch: 28 }];
  return ws;
}

function buildPhotoGallerySheet(): XLSX.WorkSheet {
  const header = ["Filename", "URL", "Description", "View in Browser"];
  const rows: (string | number)[][] = [header];

  for (const photo of PUBLIC_PHOTOS) {
    const url = assetUrl(photo.filename);
    rows.push([photo.filename, url, photo.description, url]);
  }

  const ws = XLSX.utils.aoa_to_sheet(rows);

  // Add hyperlinks on URL column (c=1) and View column (c=3)
  PUBLIC_PHOTOS.forEach((photo, i) => {
    const url = assetUrl(photo.filename);
    const urlCell  = XLSX.utils.encode_cell({ r: i + 1, c: 1 });
    const viewCell = XLSX.utils.encode_cell({ r: i + 1, c: 3 });
    ws[urlCell]  = { v: url, l: { Target: url, Tooltip: `View ${photo.filename}` } };
    ws[viewCell] = { v: "Open photo →", l: { Target: url, Tooltip: `View ${photo.filename}` } };
  });

  ws["!cols"] = [{ wch: 18 }, { wch: 52 }, { wch: 36 }, { wch: 18 }];
  return ws;
}

function buildReferenceDocumentsSheet(): XLSX.WorkSheet {
  const header = ["Document Name", "Format", "Relevant Equipment", "Description", "Download URL"];
  const rows: (string | number)[][] = [header];

  for (const doc of PUBLIC_DOCUMENTS) {
    const url    = assetUrl(doc.filename);
    const types  = doc.relevantTypes.join(", ");
    rows.push([doc.filename, doc.format, types, doc.description, url]);
  }

  const ws = XLSX.utils.aoa_to_sheet(rows);

  // Add hyperlinks on URL column (c=4)
  PUBLIC_DOCUMENTS.forEach((doc, i) => {
    const url      = assetUrl(doc.filename);
    const cellAddr = XLSX.utils.encode_cell({ r: i + 1, c: 4 });
    ws[cellAddr]   = { v: url, l: { Target: url, Tooltip: `Download ${doc.filename}` } };
  });

  ws["!cols"] = [
    { wch: 48 }, { wch: 8 }, { wch: 26 }, { wch: 38 }, { wch: 52 },
  ];

  return ws;
}

/**
 * Generates and triggers a download of the complete WVRTP inspection workbook.
 * The workbook includes all local inspection records plus reference data wired
 * to the photos and documents served from the app's public folder.
 */
export function exportInspectionWorkbook(records: InspectionRecord[]): void {
  const wb = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(wb, buildDashboardSheet(records),          "Dashboard");
  XLSX.utils.book_append_sheet(wb, buildInspectionLogSheet(records),      "Inspection Log");
  XLSX.utils.book_append_sheet(wb, buildEquipmentRegistrySheet(),          "Equipment Registry");
  XLSX.utils.book_append_sheet(wb, buildChecklistTemplatesSheet(),         "Checklist Templates");
  XLSX.utils.book_append_sheet(wb, buildPhotoGallerySheet(),               "Photo Gallery");
  XLSX.utils.book_append_sheet(wb, buildReferenceDocumentsSheet(),         "Reference Documents");

  const datestamp = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `WVRTP-Inspection-Workbook-${datestamp}.xlsx`);
}
